FROM nvidia/cuda:12.6.0-cudnn-devel-ubuntu20.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 python3-pip git curl

RUN pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu126/torch_stable.html

COPY test.py .

CMD ["python3", "test.py"]