from classification.gather_data import gather_indo_qa, gather_musique_data, gather_qasina_data
from classification.classify import classify_indo_qa, classify_musique
from classification.build_cache import build_cache_elastic